[2024-01-19T21:00:55.565-0300] {processor.py:157} INFO - Started process (PID=86839) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:00:55.566-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T21:00:55.566-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:00:55.566-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:00:55.568-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:00:55.568-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T21:00:55.568-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:00:55.568-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T21:00:55.568-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:00:55.574-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.011 seconds
[2024-01-19T21:02:16.463-0300] {processor.py:157} INFO - Started process (PID=87078) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:02:16.495-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T21:02:16.496-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:02:16.496-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:02:16.498-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:02:16.497-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T21:02:16.498-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:02:16.498-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T21:02:16.498-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:02:16.504-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.044 seconds
[2024-01-19T21:03:12.971-0300] {processor.py:157} INFO - Started process (PID=87246) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:03:13.003-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T21:03:13.004-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:03:13.004-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:03:13.006-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:03:13.006-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T21:03:13.006-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:03:13.006-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T21:03:13.007-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:03:13.013-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.045 seconds
[2024-01-19T21:04:08.182-0300] {processor.py:157} INFO - Started process (PID=87417) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:04:08.214-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T21:04:08.214-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:04:08.214-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:04:08.217-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:04:08.216-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T21:04:08.217-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:04:08.217-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T21:04:08.217-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:04:08.223-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2024-01-19T21:05:06.113-0300] {processor.py:157} INFO - Started process (PID=87587) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:05:06.145-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T21:05:06.146-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:05:06.145-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:05:06.148-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:05:06.147-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T21:05:06.148-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:05:06.148-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T21:05:06.148-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:05:06.154-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2024-01-19T21:06:06.198-0300] {processor.py:157} INFO - Started process (PID=87755) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:06:06.230-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T21:06:06.230-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:06:06.230-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:06:06.232-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:06:06.232-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T21:06:06.233-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:06:06.233-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T21:06:06.233-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:06:06.239-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2024-01-19T21:07:03.276-0300] {processor.py:157} INFO - Started process (PID=87922) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:07:03.308-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T21:07:03.309-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:07:03.309-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:07:03.311-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:07:03.311-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T21:07:03.311-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:07:03.311-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T21:07:03.311-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:07:03.318-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2024-01-19T21:07:59.153-0300] {processor.py:157} INFO - Started process (PID=88088) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:07:59.185-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T21:07:59.185-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:07:59.185-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:07:59.187-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:07:59.187-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T21:07:59.188-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:07:59.188-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T21:07:59.188-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:07:59.194-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.044 seconds
[2024-01-19T21:09:11.911-0300] {processor.py:157} INFO - Started process (PID=88295) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:09:11.943-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T21:09:11.944-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:09:11.944-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:09:11.946-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:09:11.946-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T21:09:11.946-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:09:11.946-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T21:09:11.946-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:09:11.953-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.044 seconds
[2024-01-19T21:10:10.140-0300] {processor.py:157} INFO - Started process (PID=88468) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:10:10.147-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T21:10:10.147-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:10:10.147-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:10:10.150-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:10:10.149-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T21:10:10.150-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:10:10.150-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T21:10:10.150-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:10:10.156-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2024-01-19T21:11:05.945-0300] {processor.py:157} INFO - Started process (PID=88637) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:11:05.948-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T21:11:05.949-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:11:05.949-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:11:05.951-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:11:05.951-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T21:11:05.951-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:11:05.951-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T21:11:05.951-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:11:05.958-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2024-01-19T21:12:12.673-0300] {processor.py:157} INFO - Started process (PID=88833) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:12:12.705-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T21:12:12.706-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:12:12.705-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:12:12.708-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:12:12.707-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T21:12:12.708-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:12:12.708-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T21:12:12.708-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:12:12.714-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2024-01-19T21:13:08.655-0300] {processor.py:157} INFO - Started process (PID=89001) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:13:08.687-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T21:13:08.688-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:13:08.688-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:13:08.690-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:13:08.690-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T21:13:08.690-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:13:08.690-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T21:13:08.690-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:13:08.697-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.044 seconds
[2024-01-19T21:14:05.000-0300] {processor.py:157} INFO - Started process (PID=89179) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:14:05.032-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T21:14:05.033-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:14:05.032-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:14:05.035-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:14:05.034-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T21:14:05.035-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:14:05.035-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T21:14:05.035-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:14:05.041-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.044 seconds
[2024-01-19T21:15:05.746-0300] {processor.py:157} INFO - Started process (PID=89363) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:15:05.778-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T21:15:05.779-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:15:05.779-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:15:05.781-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:15:05.781-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T21:15:05.781-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:15:05.781-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T21:15:05.781-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:15:05.787-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2024-01-19T21:16:05.650-0300] {processor.py:157} INFO - Started process (PID=89534) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:16:05.668-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T21:16:05.669-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:16:05.668-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:16:05.671-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:16:05.671-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T21:16:05.671-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:16:05.671-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T21:16:05.671-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:16:05.677-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2024-01-19T21:17:23.276-0300] {processor.py:157} INFO - Started process (PID=89764) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:17:23.309-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T21:17:23.309-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:17:23.309-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:17:23.311-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:17:23.311-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T21:17:23.311-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:17:23.311-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T21:17:23.311-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:17:23.317-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2024-01-19T21:18:29.840-0300] {processor.py:157} INFO - Started process (PID=89987) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:18:29.872-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T21:18:29.872-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:18:29.872-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:18:29.874-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:18:29.874-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T21:18:29.874-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:18:29.874-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T21:18:29.874-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:18:29.882-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.044 seconds
[2024-01-19T21:19:37.127-0300] {processor.py:157} INFO - Started process (PID=90207) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:19:37.154-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T21:19:37.154-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:19:37.154-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:19:37.156-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:19:37.156-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T21:19:37.157-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:19:37.157-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T21:19:37.157-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:19:37.163-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.038 seconds
[2024-01-19T21:20:22.495-0300] {processor.py:157} INFO - Started process (PID=90306) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:20:22.527-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T21:20:22.528-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:20:22.528-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:20:22.530-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:20:22.530-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T21:20:22.530-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:20:22.530-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T21:20:22.530-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:20:22.537-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.044 seconds
[2024-01-19T21:21:13.873-0300] {processor.py:157} INFO - Started process (PID=90469) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:21:13.905-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T21:21:13.906-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:21:13.906-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:21:13.908-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:21:13.908-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T21:21:13.908-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:21:13.908-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T21:21:13.908-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:21:13.915-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2024-01-19T21:22:08.771-0300] {processor.py:157} INFO - Started process (PID=90633) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:22:08.803-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T21:22:08.804-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:22:08.804-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:22:08.806-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:22:08.806-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T21:22:08.806-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:22:08.806-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T21:22:08.806-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:22:08.813-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.044 seconds
[2024-01-19T21:23:05.774-0300] {processor.py:157} INFO - Started process (PID=90802) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:23:05.798-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T21:23:05.799-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:23:05.799-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:23:05.801-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:23:05.801-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T21:23:05.801-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:23:05.801-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T21:23:05.801-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:23:05.808-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.036 seconds
[2024-01-19T21:24:01.310-0300] {processor.py:157} INFO - Started process (PID=90973) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:24:01.342-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T21:24:01.343-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:24:01.343-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:24:01.345-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:24:01.345-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T21:24:01.345-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:24:01.345-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T21:24:01.346-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:24:01.352-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.044 seconds
[2024-01-19T21:25:20.677-0300] {processor.py:157} INFO - Started process (PID=91211) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:25:20.709-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T21:25:20.710-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:25:20.710-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:25:20.712-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:25:20.712-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T21:25:20.712-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:25:20.712-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T21:25:20.712-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:25:20.719-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.044 seconds
[2024-01-19T21:26:17.902-0300] {processor.py:157} INFO - Started process (PID=91383) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:26:17.934-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T21:26:17.934-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:26:17.934-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:26:17.936-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:26:17.936-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T21:26:17.937-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:26:17.937-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T21:26:17.937-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:26:17.943-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.044 seconds
[2024-01-19T21:27:12.766-0300] {processor.py:157} INFO - Started process (PID=91548) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:27:12.786-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T21:27:12.787-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:27:12.786-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:27:12.789-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:27:12.788-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T21:27:12.789-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:27:12.789-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T21:27:12.789-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:27:12.796-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2024-01-19T21:28:10.504-0300] {processor.py:157} INFO - Started process (PID=91715) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:28:10.505-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T21:28:10.505-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:28:10.505-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:28:10.508-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:28:10.507-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T21:28:10.508-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:28:10.508-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T21:28:10.508-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:28:10.514-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2024-01-19T21:29:08.711-0300] {processor.py:157} INFO - Started process (PID=91889) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:29:08.743-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T21:29:08.743-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:29:08.743-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:29:08.746-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:29:08.745-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T21:29:08.746-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:29:08.746-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T21:29:08.746-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:29:08.752-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.044 seconds
[2024-01-19T21:30:11.797-0300] {processor.py:157} INFO - Started process (PID=92075) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:30:11.829-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T21:30:11.830-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:30:11.829-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:30:11.832-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:30:11.831-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T21:30:11.832-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:30:11.832-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T21:30:11.832-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:30:11.838-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2024-01-19T21:31:08.421-0300] {processor.py:157} INFO - Started process (PID=92245) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:31:08.454-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T21:31:08.454-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:31:08.454-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:31:08.456-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:31:08.456-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T21:31:08.457-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:31:08.457-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T21:31:08.457-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:31:08.463-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.044 seconds
[2024-01-19T21:32:09.493-0300] {processor.py:157} INFO - Started process (PID=92442) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:32:09.526-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T21:32:09.526-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:32:09.526-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:32:09.528-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:32:09.528-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T21:32:09.528-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:32:09.528-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T21:32:09.529-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:32:09.535-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.044 seconds
[2024-01-19T21:33:05.161-0300] {processor.py:157} INFO - Started process (PID=92608) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:33:05.193-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T21:33:05.193-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:33:05.193-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:33:05.196-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:33:05.195-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T21:33:05.196-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:33:05.196-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T21:33:05.196-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:33:05.202-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.044 seconds
[2024-01-19T21:34:00.792-0300] {processor.py:157} INFO - Started process (PID=92780) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:34:00.824-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T21:34:00.824-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:34:00.824-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:34:00.827-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:34:00.826-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T21:34:00.827-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:34:00.827-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T21:34:00.827-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:34:00.833-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.044 seconds
[2024-01-19T21:35:13.731-0300] {processor.py:157} INFO - Started process (PID=92990) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:35:13.764-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T21:35:13.764-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:35:13.764-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:35:13.767-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:35:13.766-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T21:35:13.767-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:35:13.767-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T21:35:13.767-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:35:13.773-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.044 seconds
[2024-01-19T21:36:10.250-0300] {processor.py:157} INFO - Started process (PID=93161) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:36:10.251-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T21:36:10.251-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:36:10.251-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:36:10.254-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:36:10.253-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T21:36:10.254-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:36:10.254-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T21:36:10.254-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:36:10.260-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2024-01-19T21:37:17.560-0300] {processor.py:157} INFO - Started process (PID=93355) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:37:17.592-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T21:37:17.593-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:37:17.592-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:37:17.595-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:37:17.594-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T21:37:17.595-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:37:17.595-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T21:37:17.595-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:37:17.601-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.044 seconds
[2024-01-19T21:38:28.826-0300] {processor.py:157} INFO - Started process (PID=93546) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:38:28.826-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T21:38:28.827-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:38:28.826-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:38:28.829-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:38:28.828-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T21:38:28.829-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:38:28.829-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T21:38:28.829-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:38:28.838-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2024-01-19T21:39:42.829-0300] {processor.py:157} INFO - Started process (PID=93827) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:39:42.861-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T21:39:42.862-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:39:42.861-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:39:42.864-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:39:42.863-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T21:39:42.864-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:39:42.864-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T21:39:42.864-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:39:42.870-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2024-01-19T21:40:44.721-0300] {processor.py:157} INFO - Started process (PID=93994) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:40:44.753-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T21:40:44.753-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:40:44.753-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:40:44.755-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:40:44.755-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T21:40:44.756-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:40:44.756-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T21:40:44.756-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:40:44.761-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2024-01-19T21:41:50.192-0300] {processor.py:157} INFO - Started process (PID=94206) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:41:50.193-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T21:41:50.193-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:41:50.193-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:41:50.195-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:41:50.195-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T21:41:50.195-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:41:50.195-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T21:41:50.195-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:41:50.201-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.011 seconds
[2024-01-19T21:42:46.882-0300] {processor.py:157} INFO - Started process (PID=94375) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:42:46.914-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T21:42:46.914-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:42:46.914-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:42:46.916-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:42:46.916-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T21:42:46.916-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:42:46.916-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T21:42:46.916-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:42:46.922-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2024-01-19T21:44:04.737-0300] {processor.py:157} INFO - Started process (PID=94578) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:44:04.769-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T21:44:04.769-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:44:04.769-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:44:04.771-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:44:04.771-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T21:44:04.771-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:44:04.771-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T21:44:04.772-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:44:04.777-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2024-01-19T21:45:02.598-0300] {processor.py:157} INFO - Started process (PID=94749) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:45:02.610-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T21:45:02.611-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:45:02.611-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:45:02.613-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:45:02.612-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T21:45:02.613-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:45:02.613-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T21:45:02.613-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:45:02.620-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2024-01-19T21:46:02.605-0300] {processor.py:157} INFO - Started process (PID=94920) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:46:02.606-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T21:46:02.606-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:46:02.606-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:46:02.608-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:46:02.608-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T21:46:02.609-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:46:02.608-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T21:46:02.609-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:46:02.615-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2024-01-19T21:47:05.577-0300] {processor.py:157} INFO - Started process (PID=95117) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:47:05.578-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T21:47:05.579-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:47:05.579-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:47:05.581-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:47:05.581-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T21:47:05.581-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:47:05.581-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T21:47:05.581-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:47:05.587-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.013 seconds
[2024-01-19T21:48:02.645-0300] {processor.py:157} INFO - Started process (PID=95282) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:48:02.646-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T21:48:02.646-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:48:02.646-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:48:02.649-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:48:02.648-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T21:48:02.649-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:48:02.649-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T21:48:02.649-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:48:02.655-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2024-01-19T21:49:17.321-0300] {processor.py:157} INFO - Started process (PID=95512) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:49:17.353-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T21:49:17.354-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:49:17.354-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:49:17.356-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:49:17.356-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T21:49:17.356-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:49:17.356-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T21:49:17.356-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:49:17.362-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2024-01-19T21:50:16.581-0300] {processor.py:157} INFO - Started process (PID=95677) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:50:16.613-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T21:50:16.613-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:50:16.613-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:50:16.615-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:50:16.615-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T21:50:16.616-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:50:16.616-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T21:50:16.616-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:50:16.622-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2024-01-19T21:51:12.729-0300] {processor.py:157} INFO - Started process (PID=95859) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:51:12.761-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T21:51:12.762-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:51:12.761-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:51:12.764-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:51:12.763-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T21:51:12.764-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:51:12.764-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T21:51:12.764-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:51:12.769-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2024-01-19T21:52:20.197-0300] {processor.py:157} INFO - Started process (PID=96042) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:52:20.230-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T21:52:20.230-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:52:20.230-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:52:20.232-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:52:20.232-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T21:52:20.232-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:52:20.232-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T21:52:20.232-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:52:20.238-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2024-01-19T21:53:17.758-0300] {processor.py:157} INFO - Started process (PID=96209) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:53:17.790-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T21:53:17.790-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:53:17.790-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:53:17.792-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:53:17.792-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T21:53:17.793-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:53:17.793-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T21:53:17.793-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:53:17.798-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2024-01-19T21:54:13.522-0300] {processor.py:157} INFO - Started process (PID=96383) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:54:13.554-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T21:54:13.555-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:54:13.554-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:54:13.557-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:54:13.556-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T21:54:13.557-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:54:13.557-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T21:54:13.557-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:54:13.563-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2024-01-19T21:55:13.149-0300] {processor.py:157} INFO - Started process (PID=96571) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:55:13.181-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T21:55:13.182-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:55:13.181-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:55:13.184-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:55:13.183-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T21:55:13.184-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:55:13.184-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T21:55:13.184-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:55:13.190-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2024-01-19T21:56:09.727-0300] {processor.py:157} INFO - Started process (PID=96738) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:56:09.759-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T21:56:09.760-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:56:09.760-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:56:09.762-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:56:09.762-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T21:56:09.762-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:56:09.762-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T21:56:09.762-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:56:09.768-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2024-01-19T21:57:11.721-0300] {processor.py:157} INFO - Started process (PID=96918) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:57:11.753-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T21:57:11.754-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:57:11.754-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:57:11.756-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:57:11.756-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T21:57:11.756-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:57:11.756-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T21:57:11.756-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:57:11.762-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2024-01-19T21:58:07.451-0300] {processor.py:157} INFO - Started process (PID=97087) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:58:07.452-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T21:58:07.452-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:58:07.452-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:58:07.454-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:58:07.454-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T21:58:07.454-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:58:07.454-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T21:58:07.454-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:58:07.460-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.011 seconds
[2024-01-19T21:59:20.413-0300] {processor.py:157} INFO - Started process (PID=97325) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:59:20.446-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T21:59:20.446-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:59:20.446-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:59:20.448-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:59:20.448-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T21:59:20.448-0300] {logging_mixin.py:154} INFO - [2024-01-19T21:59:20.448-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T21:59:20.448-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T21:59:20.454-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2024-01-19T22:00:19.013-0300] {processor.py:157} INFO - Started process (PID=97492) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:00:19.045-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T22:00:19.045-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:00:19.045-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:00:19.047-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:00:19.047-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T22:00:19.048-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:00:19.047-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T22:00:19.048-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:00:19.053-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2024-01-19T22:01:53.692-0300] {processor.py:157} INFO - Started process (PID=97742) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:01:53.724-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T22:01:53.725-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:01:53.725-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:01:53.727-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:01:53.727-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T22:01:53.727-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:01:53.727-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T22:01:53.727-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:01:53.733-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2024-01-19T22:02:59.772-0300] {processor.py:157} INFO - Started process (PID=97954) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:02:59.804-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T22:02:59.804-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:02:59.804-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:02:59.806-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:02:59.806-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T22:02:59.806-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:02:59.806-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T22:02:59.806-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:02:59.812-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2024-01-19T22:04:02.933-0300] {processor.py:157} INFO - Started process (PID=98130) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:04:02.934-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T22:04:02.934-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:04:02.934-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:04:02.936-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:04:02.936-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T22:04:02.936-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:04:02.936-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T22:04:02.937-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:04:02.942-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.011 seconds
[2024-01-19T22:05:09.937-0300] {processor.py:157} INFO - Started process (PID=98325) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:05:09.969-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T22:05:09.970-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:05:09.970-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:05:09.972-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:05:09.972-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T22:05:09.972-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:05:09.972-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T22:05:09.972-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:05:09.978-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2024-01-19T22:06:13.681-0300] {processor.py:157} INFO - Started process (PID=98508) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:06:13.713-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T22:06:13.714-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:06:13.713-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:06:13.716-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:06:13.716-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T22:06:13.717-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:06:13.717-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T22:06:13.717-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:06:13.723-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.044 seconds
[2024-01-19T22:07:10.069-0300] {processor.py:157} INFO - Started process (PID=98679) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:07:10.101-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T22:07:10.102-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:07:10.102-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:07:10.104-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:07:10.103-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T22:07:10.104-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:07:10.104-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T22:07:10.104-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:07:10.110-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2024-01-19T22:08:23.501-0300] {processor.py:157} INFO - Started process (PID=98890) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:08:23.502-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T22:08:23.502-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:08:23.502-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:08:23.504-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:08:23.504-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T22:08:23.504-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:08:23.504-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T22:08:23.504-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:08:23.510-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.011 seconds
[2024-01-19T22:09:17.553-0300] {processor.py:157} INFO - Started process (PID=99057) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:09:17.585-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T22:09:17.586-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:09:17.585-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:09:17.588-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:09:17.587-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T22:09:17.588-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:09:17.588-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T22:09:17.588-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:09:17.594-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2024-01-19T22:10:10.950-0300] {processor.py:157} INFO - Started process (PID=99228) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:10:10.982-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T22:10:10.983-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:10:10.982-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:10:10.985-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:10:10.984-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T22:10:10.985-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:10:10.985-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T22:10:10.985-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:10:10.991-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2024-01-19T22:11:11.469-0300] {processor.py:157} INFO - Started process (PID=99394) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:11:11.501-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T22:11:11.502-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:11:11.502-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:11:11.504-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:11:11.504-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T22:11:11.504-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:11:11.504-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T22:11:11.504-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:11:11.510-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2024-01-19T22:12:07.926-0300] {processor.py:157} INFO - Started process (PID=99563) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:12:07.958-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T22:12:07.959-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:12:07.958-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:12:07.961-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:12:07.960-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T22:12:07.961-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:12:07.961-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T22:12:07.961-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:12:07.967-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2024-01-19T22:13:16.583-0300] {processor.py:157} INFO - Started process (PID=99865) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:13:16.584-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T22:13:16.584-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:13:16.584-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:13:16.586-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:13:16.586-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T22:13:16.586-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:13:16.586-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T22:13:16.587-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:13:16.593-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2024-01-19T22:14:13.301-0300] {processor.py:157} INFO - Started process (PID=101201) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:14:13.301-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T22:14:13.302-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:14:13.302-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:14:13.304-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:14:13.303-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T22:14:13.304-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:14:13.304-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T22:14:13.304-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:14:13.310-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.011 seconds
[2024-01-19T22:15:10.057-0300] {processor.py:157} INFO - Started process (PID=101384) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:15:10.059-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T22:15:10.059-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:15:10.059-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:15:10.061-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:15:10.061-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T22:15:10.062-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:15:10.062-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T22:15:10.062-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:15:10.068-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.014 seconds
[2024-01-19T22:16:14.565-0300] {processor.py:157} INFO - Started process (PID=101579) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:16:14.597-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T22:16:14.597-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:16:14.597-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:16:14.599-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:16:14.599-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T22:16:14.600-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:16:14.600-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T22:16:14.600-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:16:14.606-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.044 seconds
[2024-01-19T22:17:09.596-0300] {processor.py:157} INFO - Started process (PID=101747) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:17:09.629-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T22:17:09.629-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:17:09.629-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:17:09.631-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:17:09.631-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T22:17:09.631-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:17:09.631-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T22:17:09.631-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:17:09.637-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2024-01-19T22:18:06.777-0300] {processor.py:157} INFO - Started process (PID=101913) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:18:06.809-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T22:18:06.809-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:18:06.809-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:18:06.812-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:18:06.811-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T22:18:06.812-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:18:06.812-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T22:18:06.812-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:18:06.818-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2024-01-19T22:19:04.801-0300] {processor.py:157} INFO - Started process (PID=102090) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:19:04.833-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T22:19:04.834-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:19:04.834-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:19:04.836-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:19:04.835-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T22:19:04.836-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:19:04.836-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T22:19:04.836-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:19:04.842-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2024-01-19T22:20:06.673-0300] {processor.py:157} INFO - Started process (PID=102260) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:20:06.705-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T22:20:06.706-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:20:06.705-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:20:06.708-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:20:06.707-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T22:20:06.708-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:20:06.708-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T22:20:06.708-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:20:06.714-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2024-01-19T22:21:07.934-0300] {processor.py:157} INFO - Started process (PID=102452) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:21:07.966-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T22:21:07.966-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:21:07.966-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:21:07.969-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:21:07.968-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T22:21:07.969-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:21:07.969-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T22:21:07.969-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:21:07.975-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2024-01-19T22:22:15.361-0300] {processor.py:157} INFO - Started process (PID=102638) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:22:15.393-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T22:22:15.393-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:22:15.393-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:22:15.396-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:22:15.395-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T22:22:15.396-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:22:15.396-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T22:22:15.396-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:22:15.401-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2024-01-19T22:23:13.704-0300] {processor.py:157} INFO - Started process (PID=102806) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:23:13.736-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T22:23:13.736-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:23:13.736-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:23:13.738-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:23:13.738-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T22:23:13.739-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:23:13.739-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T22:23:13.739-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:23:13.744-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2024-01-19T22:24:26.041-0300] {processor.py:157} INFO - Started process (PID=103021) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:24:26.047-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T22:24:26.048-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:24:26.048-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:24:26.050-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:24:26.050-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T22:24:26.050-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:24:26.050-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T22:24:26.050-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:24:26.056-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2024-01-19T22:25:31.449-0300] {processor.py:157} INFO - Started process (PID=103242) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:25:31.481-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T22:25:31.482-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:25:31.481-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:25:31.484-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:25:31.483-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T22:25:31.484-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:25:31.484-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T22:25:31.484-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:25:31.490-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2024-01-19T22:26:42.753-0300] {processor.py:157} INFO - Started process (PID=103484) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:26:42.785-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T22:26:42.786-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:26:42.785-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:26:42.788-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:26:42.787-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T22:26:42.788-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:26:42.788-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T22:26:42.788-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:26:42.794-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2024-01-19T22:27:59.599-0300] {processor.py:157} INFO - Started process (PID=103685) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:27:59.600-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T22:27:59.600-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:27:59.600-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:27:59.602-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:27:59.602-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T22:27:59.602-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:27:59.602-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T22:27:59.602-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:27:59.609-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2024-01-19T22:29:12.194-0300] {processor.py:157} INFO - Started process (PID=103912) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:29:12.226-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T22:29:12.226-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:29:12.226-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:29:12.228-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:29:12.228-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T22:29:12.229-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:29:12.229-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T22:29:12.229-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:29:12.234-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2024-01-19T22:30:11.352-0300] {processor.py:157} INFO - Started process (PID=104086) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:30:11.384-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T22:30:11.385-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:30:11.385-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:30:11.387-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:30:11.387-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T22:30:11.387-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:30:11.387-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T22:30:11.387-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:30:11.393-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2024-01-19T22:31:09.409-0300] {processor.py:157} INFO - Started process (PID=104253) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:31:09.441-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T22:31:09.441-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:31:09.441-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:31:09.443-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:31:09.443-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T22:31:09.444-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:31:09.443-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T22:31:09.444-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:31:09.450-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2024-01-19T22:32:04.042-0300] {processor.py:157} INFO - Started process (PID=104418) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:32:04.075-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T22:32:04.075-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:32:04.075-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:32:04.077-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:32:04.077-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T22:32:04.078-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:32:04.077-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T22:32:04.078-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:32:04.084-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2024-01-19T22:32:59.204-0300] {processor.py:157} INFO - Started process (PID=104584) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:32:59.236-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T22:32:59.236-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:32:59.236-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:32:59.238-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:32:59.238-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T22:32:59.238-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:32:59.238-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T22:32:59.239-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:32:59.245-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2024-01-19T22:34:12.016-0300] {processor.py:157} INFO - Started process (PID=104802) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:34:12.048-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T22:34:12.049-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:34:12.048-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:34:12.052-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:34:12.051-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T22:34:12.052-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:34:12.052-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T22:34:12.052-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:34:12.058-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.044 seconds
[2024-01-19T22:35:15.692-0300] {processor.py:157} INFO - Started process (PID=105003) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:35:15.724-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T22:35:15.725-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:35:15.724-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:35:15.727-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:35:15.726-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T22:35:15.727-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:35:15.727-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T22:35:15.727-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:35:15.733-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.044 seconds
[2024-01-19T22:36:12.018-0300] {processor.py:157} INFO - Started process (PID=105171) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:36:12.050-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T22:36:12.050-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:36:12.050-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:36:12.053-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:36:12.052-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T22:36:12.053-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:36:12.053-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T22:36:12.053-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:36:12.059-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2024-01-19T22:37:06.344-0300] {processor.py:157} INFO - Started process (PID=105336) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:37:06.396-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T22:37:06.397-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:37:06.396-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:37:06.399-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:37:06.398-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T22:37:06.399-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:37:06.399-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T22:37:06.399-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:37:06.405-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.064 seconds
[2024-01-19T22:38:02.436-0300] {processor.py:157} INFO - Started process (PID=105502) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:38:02.436-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T22:38:02.437-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:38:02.436-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:38:02.439-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:38:02.438-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T22:38:02.439-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:38:02.439-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T22:38:02.439-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:38:02.445-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2024-01-19T22:39:12.085-0300] {processor.py:157} INFO - Started process (PID=105721) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:39:12.117-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T22:39:12.118-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:39:12.118-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:39:12.120-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:39:12.120-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T22:39:12.120-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:39:12.120-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T22:39:12.120-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:39:12.126-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2024-01-19T22:40:11.120-0300] {processor.py:157} INFO - Started process (PID=105889) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:40:11.152-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T22:40:11.153-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:40:11.152-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:40:11.155-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:40:11.154-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T22:40:11.155-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:40:11.155-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T22:40:11.155-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:40:11.161-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2024-01-19T22:41:05.521-0300] {processor.py:157} INFO - Started process (PID=106056) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:41:05.553-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T22:41:05.553-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:41:05.553-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:41:05.555-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:41:05.555-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T22:41:05.555-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:41:05.555-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T22:41:05.555-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:41:05.561-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2024-01-19T22:42:01.162-0300] {processor.py:157} INFO - Started process (PID=106222) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:42:01.194-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T22:42:01.195-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:42:01.194-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:42:01.197-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:42:01.196-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T22:42:01.197-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:42:01.197-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T22:42:01.197-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:42:01.203-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2024-01-19T22:43:10.685-0300] {processor.py:157} INFO - Started process (PID=106431) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:43:10.717-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T22:43:10.717-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:43:10.717-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:43:10.720-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:43:10.720-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T22:43:10.720-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:43:10.720-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T22:43:10.720-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:43:10.726-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.044 seconds
[2024-01-19T22:44:08.270-0300] {processor.py:157} INFO - Started process (PID=106605) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:44:08.302-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T22:44:08.302-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:44:08.302-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:44:08.304-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:44:08.304-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T22:44:08.304-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:44:08.304-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T22:44:08.305-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:44:08.311-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2024-01-19T22:45:16.206-0300] {processor.py:157} INFO - Started process (PID=106815) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:45:16.238-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T22:45:16.239-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:45:16.239-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:45:16.241-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:45:16.241-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T22:45:16.241-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:45:16.241-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T22:45:16.241-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:45:16.247-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2024-01-19T22:46:11.478-0300] {processor.py:157} INFO - Started process (PID=106982) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:46:11.510-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T22:46:11.510-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:46:11.510-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:46:11.513-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:46:11.512-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T22:46:11.513-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:46:11.513-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T22:46:11.513-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:46:11.519-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2024-01-19T22:47:20.470-0300] {processor.py:157} INFO - Started process (PID=107186) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:47:20.502-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T22:47:20.503-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:47:20.502-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:47:20.505-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:47:20.504-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T22:47:20.505-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:47:20.505-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T22:47:20.505-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:47:20.511-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2024-01-19T22:48:16.177-0300] {processor.py:157} INFO - Started process (PID=107352) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:48:16.209-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T22:48:16.210-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:48:16.210-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:48:16.212-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:48:16.212-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T22:48:16.212-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:48:16.212-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T22:48:16.212-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:48:16.219-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2024-01-19T22:49:09.694-0300] {processor.py:157} INFO - Started process (PID=107532) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:49:09.695-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T22:49:09.695-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:49:09.695-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:49:09.697-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:49:09.697-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T22:49:09.697-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:49:09.697-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T22:49:09.697-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:49:09.703-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.011 seconds
[2024-01-19T22:50:06.218-0300] {processor.py:157} INFO - Started process (PID=107837) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:50:06.250-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T22:50:06.251-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:50:06.251-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:50:06.253-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:50:06.253-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T22:50:06.253-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:50:06.253-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T22:50:06.253-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:50:06.260-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.044 seconds
[2024-01-19T22:51:17.710-0300] {processor.py:157} INFO - Started process (PID=108205) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:51:17.780-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T22:51:17.781-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:51:17.781-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:51:17.783-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:51:17.783-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T22:51:17.783-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:51:17.783-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T22:51:17.783-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:51:17.789-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.081 seconds
[2024-01-19T22:52:16.913-0300] {processor.py:157} INFO - Started process (PID=108434) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:52:16.915-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T22:52:16.916-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:52:16.915-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:52:16.918-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:52:16.917-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T22:52:16.918-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:52:16.918-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T22:52:16.918-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:52:16.925-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2024-01-19T22:53:24.470-0300] {processor.py:157} INFO - Started process (PID=108698) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:53:24.476-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T22:53:24.477-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:53:24.476-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:53:24.479-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:53:24.478-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T22:53:24.479-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:53:24.479-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T22:53:24.479-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:53:24.485-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2024-01-19T22:54:21.592-0300] {processor.py:157} INFO - Started process (PID=108934) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:54:21.625-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T22:54:21.625-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:54:21.625-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:54:21.627-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:54:21.627-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T22:54:21.628-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:54:21.628-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T22:54:21.628-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:54:21.635-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.044 seconds
[2024-01-19T22:55:50.703-0300] {processor.py:157} INFO - Started process (PID=109366) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:55:50.704-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T22:55:50.704-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:55:50.704-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:55:50.706-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:55:50.706-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T22:55:50.706-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:55:50.706-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T22:55:50.707-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:55:50.713-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2024-01-19T22:57:16.761-0300] {processor.py:157} INFO - Started process (PID=109663) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:57:16.793-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T22:57:16.793-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:57:16.793-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:57:16.796-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:57:16.795-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T22:57:16.796-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:57:16.796-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T22:57:16.796-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:57:16.802-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2024-01-19T22:58:12.680-0300] {processor.py:157} INFO - Started process (PID=109853) to work on /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:58:12.681-0300] {processor.py:829} INFO - Processing file /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-19T22:58:12.681-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:58:12.681-0300] {dagbag.py:536} INFO - Filling up the DagBag from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:58:12.684-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:58:12.683-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-19T22:58:12.684-0300] {logging_mixin.py:154} INFO - [2024-01-19T22:58:12.684-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-19T22:58:12.684-0300] {processor.py:841} WARNING - No viable dags retrieved from /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-19T22:58:12.692-0300] {processor.py:179} INFO - Processing /home/felipe/.local/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.013 seconds
